version: '3'

services:
  reviews-service:
    build:
      context: .
    image: janschultecom/reviews-service
    ports:
      - 8080:8080
    volumes:
      - ./reviews.json:/data/reviews.json
    environment:
      - SERVICE_HOST=0.0.0.0
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./schema/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      - API_URL=./swagger.yml
    depends_on:
      - reviews-service